### ISSUE TITLE
Where is repo installed?

### ISSUE THREAD

**Issue by atanasj** [anott03/nvim-lspinstall#13]
I tried to install the sumneko lsp for lua, however the error stated Ninja was not found. I've tried to reinstall, but it says that it is already installed.

I can't figure it out based on the script. I was hoping to delete it and try again. 

Please let me know if you need any more info. Thanks.

**Comment by atanasj** [comment]
I figured it out and all is good now. One got it up and running. Thanks!

**Comment by anott03** [comment]
Hi, apologies for not getting to this until after you figured it out. For anyone else who may be looking for it, sumneko lua should get installed to the stdpath for cache. By default this should be `$HOME/.cache/nvim`.

**Comment by atanasj** [comment]
Sorry, should have provided more information about my solution. Thanks again.
