### ISSUE TITLE
Add install command rather than function

### ISSUE THREAD

**Issue by akinsho** [anott03/nvim-lspinstall#2]
Hi 👋🏿 , thanks for making this plugin 🚀 .

This is just a minor user experience suggestion to make this easier to use. Have you considered creating a `command` so users don't have to use the `call LspInstall('name')` syntax and can just do `LspInstall <name>`
This would be similar to how `LspInstall` in the `nvim-lspconfig` used to work as well.

for example
```lua
vim.cmd [[command! -nargs=1 -complete=custom,ListLsps lua require('lspinstall').install('<q-args>')

vim.api.nvim_exec([[
 function! ListLsps(A, L, P) abort
   return v:lua.require('lspinstall').get_lsps()
 endfunction
]], '')
```

**Comment by anott03** [comment]
Hi, I appreciate the suggestion.
I have considered doing this, but my concern is that it will conflict with the `LspInstall` command that `nvim-lspconfig` provides. I don't want users to get the deprecation notice because it calls the command from lspconfig. Do you know what will happen if there are two plugins attempting to create the same command?

**Comment by akinsho** [comment]
@anott03 using `command!` allows you to override an existing command so as long as this plugin is loaded *after* lspconfig you can override the command they provide with your own, you'd just have to indicate that this step was necessary in the README. Alternatively you can pick another for the command like `InstallLsp` 🤷🏿 . I think using another command is fine for now tbh and less error prone and once lsp config removes that command you can also add the one it was using

**Comment by anott03** [comment]
@akinsho Thanks for the advice. I'll go with implementing `InstallLsp` for now.

**Comment by anott03** [comment]
All done! I'm thinking of changing the name from `InstallLsp` to `InstallLanguageServer` since this doesn't install LSP, it just installs the server. That may be included in a larger refactoring of the code.

**Comment by akinsho** [comment]
I think they new name will make sense but be a bit long to write

**Comment by akinsho** [comment]
@anott03 `nvim-lspconfig` just removed the `LspInstall` command btw

**Comment by anott03** [comment]
@akinsho Thanks for letting me know! I'll be adding that editor command as well, but for the sake of consistency, I'll leave the other two in place as well, at least for now,
